image:
  name: antora/antora:2.3.4
build:
  stage: build
  tags:
    - pbaictbuild2
  script:
    - yarn add asciidoctor-kroki 
    - node -v
    - antora --fetch --cache-dir .cache/antora --attribute page-pagination= --to-dir build antora-playbook.yml
   
  artifacts:
    paths:
    - build/
