= MC server starten met Ansible

== Intro
Stappenplan:

* Voorbereiding
* Structuur opbouwen
* Tasks toevoegen aan de role
* Testen

=== Voorbereiding
We loggen in via ssh op onze host controller dit zal de ubuntu machine zijn.
Eens aangelogd zullen we de machine up to date brengen, dit doen we door middel van volgende commando's:
----
sudo apt-get update
sudo apt-get upgrade
sudo apt install vim
----

=== Structuur opbouwen

We werken in de map ansible-project
----
cd /home/student/ansible-project
----
Eerst maken we de inventory file aan voor onze infrastructuur
----
touch inventory.yml
----
----
vim inventory.yml
----
Hierin beschrijven we de infrastructuur en hun IP's
Om te beginnen werken in een vim
----
---
  all:
    children:
      controlhosts:
        hosts:
          controlnode1:
            ansible_host: x.x.x.x
      mcservers:
        hosts:
          server:
            ansible_host: x.x.x.x
----
De volgende stap is de role aanmaken
----
mkdir roles
cd roles
ansible-galaxy init mc_deployment
cd ..
----
In deze stap maken we de play aan
----
touch mc_deployment.yml
vim mc_deployment.yml
----
Nu gaan we beschrijven op welke host deze rol uitgevoerd zal worden.
Met vim schrijven we volgend stuk in onze play: (verlaat vim met :wq om op te slaan)
----
---
- name: Deploy MC server
  hosts: server
  become: true
  role:
    mc_deployment
----
Nu voegen we deze play toe aan ons playbook:
----
vim playbook.yml
----
----
---
- import_playbook: mc_deployment.yml
----
Onze structuur zou er op dit moment als volgt moeten uitzien:
----
playbook.yml
mc_deployment.yml
roles
  mc_deployment
----
We testen even kort of onze opstelling vrij is van fouten:
----
ansible-playbook playbook.yml
----

=== Tasks toevoegen
We navigeren met vim naar de task folder van onze role, hier kunnen we in main.yml onze tasks schrijven
----
vim roles/mc_deployment/task/main.yml
----
Onze eerste task is het updaten van de yum repository. Dit doen we zo:
----
---
- name: Update yum
  yum:
    update_cache: yes
    state: latest
----
Sla dit op en test even of dit werkt met het uitvoor commando
----
ansible-playbook playbook.yml
----