= Wegwijs maken met de virtuele machines

== Wat is een virtuele machine?
We gaan nog is kort overlopen wat een virtuele machine precies is. Een virtuele machine, vaak kortweg een VM, is niet anders dan andere fysieke computers, zoals een laptop, een smartphone of een server. Het heeft een CPU, geheugen, schijven om uw bestanden op te slaan en kan indien nodig verbinding maken met internet. Hoewel de onderdelen waaruit uw computer bestaat (hardware) fysiek en tastbaar zijn, worden VM's vaak gezien als virtuele computers of door software gedefinieerde computers binnen fysieke servers, die alleen bestaan uit code.

== Hoe werkt een virtuele machine?
Virtualisatie is het proces van het maken van een op software gebaseerde, of virtuele versie van een computer, met toegewezen aantallen CPU, geheugen en opslag die is 'geleend' van een fysieke hostcomputer (zoals uw pc) en/of een externe server, zoals een server in het datacentrum van een cloudprovider. Een virtuele machine is een computerbestand (meestal een installatiekopie genoemd), dat zich als echte computer gedraagt. Het kan in een venster worden uitgevoerd als een afzonderlijke computeromgeving, vaak om een ander besturingssysteem uit te voeren, of kan zelfs functioneren als de volledige computerervaring van de gebruiker, zoals gebruikelijk op de werkcomputers van een groot aantal personen. De virtuele machine wordt gepartitioneerd van de rest van het systeem, wat inhoudt dat de software binnen een VM niet kan conflicteren met het primaire besturingssysteem van de hostcomputer.

== Wat zijn de voordelen van het gebruiken van het gebruiken van VM’s?
Terwijl virtuele machines worden uitgevoerd als afzonderlijke computers met afzonderlijke besturingssystemen en toepassingen, hebben ze het voordeel dat ze volledig onafhankelijk zijn van elkaar en de fysieke hostmachine. Met een stukje software genaamd een hypervisor, of virtuele machinebeheerder, kunt u verschillende besturingssystemen op verschillende virtuele machines tegelijk uitvoeren. Hierdoor is mogelijk om bijvoorbeeld Linux-VM's uit te voeren op een Windows-besturingssysteem, of om een eerdere versie van Windows uit te voeren op het huidige Windows-besturingssysteem.
En omdat VM's onafhankelijk van elkaar zijn, zijn ze ook zeer draagbaar. U kunt een VM op een hypervisor vrijwel onmiddellijk naar een andere hypervisor verplaatsen.

Vanwege hun flexibiliteit en portabiliteit bieden virtuele machines veel voordelen, zoals:

* Apps maken en implementeren in de cloud.
* Uitproberen van een nieuw besturingssysteem (OS), waaronder bètaversies.
* Een nieuwe omgeving installeren, zodat ontwikkelaars eenvoudiger en sneller ontwikkel- en testscenario's kunnen uitvoeren.
* Back-ups maken van uw bestaande besturingssysteem.
* Toegang tot door virussen geïnfecteerde gegevens of het uitvoeren van een oude toepassing door een ouder besturingssysteem te installeren.
* Het uitvoeren van software of apps op besturingssystemen waarvoor deze oorspronkelijk niet waren bedoeld.

== Waarvoor worden VM’s gebruikt?
Hier volgen enkele manieren waarop virtuele machines worden gebruikt:

* Apps maken en implementeren in de cloud.
* Uitproberen van een nieuw besturingssysteem (OS), waaronder bètaversies.
* Een nieuwe omgeving installeren, zodat ontwikkelaars eenvoudiger en sneller ontwikkel- en testscenario's kunnen uitvoeren.
* Back-ups maken van uw bestaande besturingssysteem.
* Toegang tot door virussen geïnfecteerde gegevens of het uitvoeren van een oude toepassing door een ouder besturingssysteem te installeren.
* Het uitvoeren van software of apps op besturingssystemen waarvoor deze oorspronkelijk niet waren bedoeld.

