=== 1 Een bredere kijk op Ansible
==== 1.1 Werken met playbooks, plays en tasks
Ansible playbooks zijn kort samengevat voorgeschreven code in een bestand. Vaak zijn dit `.yml` of `.ini` bestanden. Playbooks zorgen er voor dat bepaalde taken of code niet steeds opnieuw moeten geschreven worden om herhalende taken uit te voeren op één of meerdere machines. Het schrijven van `YAML` bestanden gebeurt met indentatie net zoals de programmeer taal python, meer over de `YAML` syntax kan je link:https://www.cloudbees.com/blog/yaml-tutorial-everything-you-need-get-started/[hier] terug vinden.


==== 1.2 Wat is een playbook precies?
Playbooks zijn scripts die bestaan uit een oplijsting van commando's. Deze commando's worden doorgestuurd naar externe machines. Ansible playbooks bieden flexibiliteit en simpliciteit voor het configureren van één of meerdere machines. Op die manier moet men niet steeds handmatig herhalende taken uitvoeren. Men kan de inhoud van een playbook eerder aanzien als een configuratie opstlling dan dat ze geschreven is in een programmeertaal.

Maar wat zit er nu echt in een playbook?
Een `playbook` is eigenlijk een lijst van `plays`. Lijsten staan het hoogste in de hirachy van een playbook. Een play wordt gedefinierd met `import_playbook`, deze importeert een lijst van plays afkomstig uit een ander bestand (meestal een rol). De import zorgt er voor dat de werk omgeving overzichtelijk blijft. Het is ook mogelijk om meteen alle plays in playbook te defineren maar zoals al eerder vermeld is dit on overzichtelijk. Een playbook bestaat dus uit meerdere `plays` en een `play` bestaat op zijn beurt uit meerdere `tasks`.



De naam van een `playbook` is het enige dat kan worden opgeroepen in een commando met het `ansible-playbook` key-word. 

TIP: **Een playbook uitvoeren kan men met `ansible-playbook naam_van_playbook.yml`**

==== 1.3 Wat is een play?
Plays zijn elementen die `roles` verbinden met een host (server) waarop ze uitgevoerd moeten worden. Op die manier weet Ansible welke hosts er worden beïnvloed en hoe. Een play kan één of meerdere `tasks` bevatten.



