=== 1 Een bredere kijk op Ansible
==== 1.1 Werken met playbooks, plays en tasks
Ansible playbooks zijn kort samengevat voorgeschreven code in een bestand. Vaak zijn dit `.yml` of `.ini` bestanden. Playbooks zorgen er voor dat bepaalde taken of code niet steeds opnieuw moeten geschreven worden om herhalende taken uit te voeren op één of meerdere machines. Het schrijven van `YAML` bestanden gebeurt met indentatie net zoals de programmeer taal python, meer over de `YAML` syntax kan je link:https://www.cloudbees.com/blog/yaml-tutorial-everything-you-need-get-started/[hier] terug vinden.


==== 1.2 Wat is een playbook precies?
Playbooks zijn scripts die bestaan uit een oplijsting van commando's. Deze commando's worden doorgestuurd naar externe machines. Ansible playbooks bieden flexibiliteit en simpliciteit voor het configureren van één of meerdere machines. Op die manier moet men niet steeds handmatig herhalende taken uitvoeren. Men kan de inhoud van een playbook eerder aanzien als een configuratie opstlling dan dat ze geschreven is in een programmeertaal.

Maar wat zit er nu echt in een playbook?
Een `playbook` is eigenlijk een lijst van `plays`. Lijsten staan het hoogste in de hirachy van een playbook. Een play wordt gedefinierd met `import_playbook`, deze importeert een lijst van plays afkomstig uit een ander bestand (meestal een rol). De import zorgt er voor dat de werk omgeving overzichtelijk blijft. Het is ook mogelijk om meteen alle plays in playbook te defineren maar zoals al eerder vermeld is dit on overzichtelijk. Een playbook bestaat dus uit meerdere `plays` en een `play` bestaat op zijn beurt uit meerdere `tasks`.



De naam van een `playbook` is het enige dat kan worden opgeroepen in een commando met het `ansible-playbook` key-word. 

TIP: **Een playbook uitvoeren kan men met `ansible-playbook naam_van_playbook.yml`**

==== 1.3 Wat is een play?
Plays zijn elementen die `roles` verbinden met een host (server) waarop ze uitgevoerd moeten worden. Op die manier weet Ansible welke hosts er worden beïnvloed en hoe. Een play kan één of meerdere `tasks` bevatten.

==== 1.4 Wat is een task?
Wat zijn `tasks` dan nog? Een task is/doet eigenlijk niets meer dan een Ansible module aanspreken. Deze weet hoe dan ook niet waar of op welke host hij wordt opgeroepen. Maar zoals al vermeld is dat de play zijn taak.

Standaard wordt elke taak op volgorde van definiëring uitgevoerd. Dit op elke machine dat werd vermeld door het `hosts` key-word. Eenmaal een taak is uitgevoerd op de doel machine(s) gaat Ansible door naar de volgende taak.
Indien een taak faalt op een host, worden voor die bepaalde host geen taken meer uitgevoerd uit de playbook (om verdere conflicten te vermeiden).


=== 2 Roles en handlers

==== 2.1 Roles
Een rol is een appart deel in Ansible en wordt niet gedefinieerd in een palybook. Roles hebben hun eigen sub-mappen onder de map `roles`. Omdat in meest van de gevallen niet alle `hosts` dezelfde configuratie nodig hebben is het vaak beter om deze op te splitsen. Hier komen `roles` in de kijker. Zij zorgen ervoor dat alles geordend blijft en dat elk deel bijvoorbeeld variabelen (`vars`) in een apart mapje worden gedefinieerd. Als men bijvoorbeeld een `task` uitvoert zal er automatisch worden gezocht achter de variabele in het bestand van de `vars` map. Zoals een `play` definieert een rol de `tasks` en `handlers`. Hoe dan ook, rollen bepalen niet op welke hosts de rol zal worden uitgevoerd. Een referentie naar een rol zal dus steeds plaats vinden in een play.

==== 2.2 Handlers
`Tasks` en `handlers` zijn eigenlijk bijna identiek. Het enige verschil met handlers is dat ze enkel worden uitgevoerd bij een oproep door het `notify` key-word. Hoe dan ook zal deze notify enkel worden doorgevoerd indien er veranderingen zijn waargenomen. Dit is bijvoorbeeld handig wanner men aanpassingen heeft gemaakt in de firewall service, en om deze aanpassingen door te voeren moet men de service herstarten.


